export const storeListData = [
  {
    type: 'Feature',
    storeId: 'store-0033',
    properties: {
      streetAddress: '23155 Katy Freeway ',
      stateCode: 'TX',
      phone: '(281) 693-8200',
      storePicURL: '',
      storeName: 'SavvyGroccer 0033',
      neighborhood: 'Grand Parkway',
      state: 'tx',
      stateName: 'texas',
      city: 'Katy',
      country: 'US',
      careers: '200000160',
      distance: '6.02',
      zipCode: '77450',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: true,
      closed: null,
      gx_id: '33',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0165',
    properties: {
      streetAddress: '24970 FM 1093 Rd.',
      stateCode: 'TX',
      phone: '(281) 371-1700',
      storePicURL: '',
      storeName: 'SavvyGroccer 0165',
      neighborhood: 'Cinco Ranch',
      state: 'tx',
      stateName: 'texas',
      city: 'Richmond',
      country: 'US',
      careers: '',
      distance: '5.2',
      zipCode: '77406',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '165',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0195',
    properties: {
      streetAddress: '2320 Highway 6',
      stateCode: 'TX',
      phone: '(281) 556-3200',
      storePicURL: '',
      storeName: 'SavvyGroccer 0195',
      neighborhood: 'West Oaks',
      state: 'tx',
      stateName: 'texas',
      city: 'Houston',
      country: 'US',
      careers: '200000167',
      distance: '5.67',
      zipCode: '77077',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '195',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-12200',
    properties: {
      streetAddress: '1223 taxes',
      stateCode: 'TN',
      phone: '(318) 324-5720',
      storePicURL: null,
      storeName: 'SavvyGroccer 12200',
      neighborhood: 'katy',
      state: 'tn',
      stateName: 'tennessee',
      city: 'Katy',
      country: 'US',
      careers: null,
      distance: '5.75',
      zipCode: '62287',
      promo1: null,
      todayTiming: 'Closed(Opens on 10/31/2024)',
      isFavStore: false,
      closed: null,
      gx_id: '12200',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0321',
    properties: {
      streetAddress: '19150 W.Bellfort street1',
      stateCode: 'TX',
      phone: '(832) 945-6788',
      storePicURL: '',
      storeName: 'SavvyGroccer 0321',
      neighborhood: 'Aliana',
      state: 'tx',
      stateName: 'texas',
      city: 'Richmond',
      country: 'US',
      careers: '',
      distance: '5.85',
      zipCode: '77407',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '321',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0012',
    properties: {
      streetAddress: '16610 Southwest Frwy',
      stateCode: 'TX',
      phone: '(281) 276-7400',
      storePicURL: '',
      storeName: 'SavvyGroccer 0012',
      neighborhood: 'Sugar Land',
      state: 'tx',
      stateName: 'texas',
      city: 'Sugar Land',
      country: 'US',
      careers: '200000155',
      distance: '12.27',
      zipCode: '77479',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '12',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0007',
    properties: {
      streetAddress: '19720 Northwest Freeway',
      stateCode: 'TX',
      phone: '(281) 517-3800',
      storePicURL: '',
      storeName: 'SavvyGroccer 0007',
      neighborhood: 'Crossroads',
      state: 'tx',
      stateName: 'texas',
      city: 'Houston',
      country: 'US',
      careers: '200000171',
      distance: '13.98',
      zipCode: '77065',
      promo1: null,
      todayTiming: 'Closed Today',
      isFavStore: false,
      closed: null,
      gx_id: '7',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0035',
    properties: {
      streetAddress: '11077 Northwest Frwy',
      stateCode: 'TX',
      phone: '(713) 613-6300',
      storePicURL: '',
      storeName: 'SavvyGroccer 0035',
      neighborhood: 'Northwest',
      state: 'tx',
      stateName: 'texas',
      city: 'Houston',
      country: 'US',
      careers: '200000162',
      distance: '16.98',
      zipCode: '77092',
      promo1: null,
      todayTiming: 'Open today from 9:00 am - 9:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '35',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0239',
    properties: {
      streetAddress: '28616 Highway 290',
      stateCode: 'TX',
      phone: '(832) 773-6300',
      storePicURL: '',
      storeName: 'SavvyGroccer 0239',
      neighborhood: 'Fairfield',
      state: 'tx',
      stateName: 'texas',
      city: 'Cypress',
      country: 'US',
      careers: '',
      distance: '17.18',
      zipCode: '77433',
      promo1: null,
      todayTiming: 'Open today from 9:00 am - 9:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '239',
    },
  },
  {
    type: 'Feature',
    storeId: 'store-0337',
    properties: {
      streetAddress: '8715-A W Loop S',
      stateCode: 'TX',
      phone: '0',
      storePicURL: null,
      storeName: 'SavvyGroccer 0337',
      neighborhood: 'Meyerland',
      state: 'tx',
      stateName: 'texas',
      city: 'Houston',
      country: 'US',
      careers: null,
      distance: '17.53',
      zipCode: '77096',
      promo1: null,
      todayTiming: 'Open today from 8:00 am - 10:00 pm',
      isFavStore: false,
      closed: null,
      gx_id: '337',
    },
  },
];
